apiVersion: v1
kind: Pod
metadata:
  name: deviceapi
spec:
  containers:
    - image: gbaeke/go-device
      name:  device
      env:
       - name:  MICRO_REGISTRY
         value:  kubernetes
       - name: MICRO_SELECTOR
         value: cache
       - name: MICRO_SERVER_ADDRESS
         value: 0.0.0.0:9090
       - name: MICRO_BROKER_ADDRESS
         value: 0.0.0.0:9091